version: "0.2"
language: en
words:
  - activedescendant
  - app-router
  - astro
  - asyncgenerator
  - asynciterable
  - better-tailwindcss
  - canonicalurl
  - changeset
  - changesets
  - codecov
  - commitizen
  - commonmark
  - cspell
  - darraghor
  - dev-dependency
  - dts
  - eslint-config
  - esmodule
  - expo
  - fetchcontent
  - flat-config
  - getentrybyslug
  - gitignore
  - importscripts
  - isnan
  - istanbul
  - jsonc
  - jsx
  - knip
  - lint-staged
  - linted
  - linter
  - llm
  - llms
  - mdx
  - monorepo
  - multilines
  - myframework
  - myoptional
  - nestjs
  - nextjs
  - nodejs
  - nogitignore
  - nonconstructor
  - nonoctal
  - nonwords
  - orchestrates
  - packagemanager
  - peer-dependency
  - peerdep
  - polyfillio
  - postpack
  - project-type
  - proptypes
  - qwik
  - root-dir
  - santi
  - santi020k
  - scopedslots
  - solidjs
  - sonarjs
  - st
  - stnl
  - stringly
  - stylistic
  - svelte
  - Tanstack
  - textnodes
  - toml
  - tsconfig
  - TSES
  - TSESLint
  - tsup
  - tsx
  - turborepo
  - typedarrays
  - typedoc
  - urql
  - v8
  - vdom
  - vitepress
  - vitest
  - opengraph
  - vue
  - weakref
  - workspace
  - workspaces
ignorePaths:
  - node_modules
  - dist
  - coverage
  - .turbo
  - .git
  - .changeset
  - pnpm-lock.yaml
  - "*.log"
  - docs
  - docs-md
  - .agent
  - "**/*.test.ts.snap"
  - packages/playground/**
  - packages/tests/src/__snapshots__/**
  - .vscode
