packages:
  - 'packages/*'
  - 'packages/playground/*'
  - 'packages/playground/libraries/*'
  - 'packages/playground/testing/*'
  - 'packages/playground/formats/*'
  - 'packages/playground/tools/*'
  - 'packages/playground/extensions/*'
