packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/playground/*'
  - 'packages/playground/libraries/*'
  - 'packages/playground/testing/*'
  - 'packages/playground/formats/*'
  - 'packages/playground/tools/*'
  - 'packages/playground/extensions/*'

overrides:
  eslint: ^10.5.0
  glob: ^13.0.6
  rimraf: ^6.1.3
  lodash: ^4.18.1
  esbuild: ^0.28.1
  path-to-regexp: ^8.4.2
  defu: ^6.1.7
  vite: ^8.0.16
