/** @type {import('typedoc').TypeDocOptions} */
export default {
  entryPoints: [
    'packages/core/src/index.ts',
    'packages/typescript/src/index.ts',
    'packages/react/src/index.ts',
    'packages/preact/src/index.ts',
    'packages/next/src/index.ts',
    'packages/nuxt/src/index.ts',
    'packages/astro/src/index.ts',
    'packages/expo/src/index.ts',
    'packages/vue/src/index.ts',
    'packages/svelte/src/index.ts',
    'packages/solid/src/index.ts',
    'packages/angular/src/index.ts',
    'packages/nest/src/index.ts',
    'packages/hono/src/index.ts',
    'packages/qwik/src/index.ts',
    'packages/react-router/src/index.ts',
    'packages/tanstack-start/src/index.ts',
    'packages/lit/src/index.ts',
    'packages/vite/src/index.ts',
    'packages/slidev/src/index.ts',
    'packages/lite/src/index.ts',
    'packages/extensions/src/index.ts',
    'packages/formats/src/index.ts',
    'packages/libraries/src/index.ts',
    'packages/testing/src/index.ts',
    'packages/tools/src/index.ts',
    'packages/integrations/src/index.ts',
    'packages/basic/src/index.ts',
    'packages/basic/src/agent-skill-generator.ts'
  ],
  out: 'docs',
  tsconfig: './tsconfig.docs.json',
  name: '@santi020k/eslint-config-basic',
  readme: './README.md',
  excludePrivate: true,
  excludeInternal: true,
  categorizeByGroup: true,
  navigationLinks: {
    GitHub: 'https://github.com/santi020k/eslint-config-basic',
    npm: 'https://www.npmjs.com/package/@santi020k/eslint-config-basic'
  }
}
